---
dist: bionic
services:
  - docker

language: python
python:
  - "3.7"

env:
#-----------------------------------------------
#
# CentOS
#
#-----------------------------------------------
  - distribution: centos-8
    playbook: sonar_scanner_3.3.0.1492
  - distribution: centos-7
    playbook: sonar_scanner_3.3.0.1492

#--------------------------------
#
# Fedora
#
#--------------------------------
  - distribution: fedora-31
    playbook: sonar_scanner_3.3.0.1492
  - distribution: fedora-30
    playbook: sonar_scanner_3.3.0.1492
  - distribution: fedora-29
    playbook: sonar_scanner_3.3.0.1492
  - distribution: fedora-28
    playbook: sonar_scanner_3.3.0.1492
  - distribution: fedora-27
    playbook: sonar_scanner_3.3.0.1492
  - distribution: fedora-26
    playbook: sonar_scanner_3.3.0.1492

#--------------------------------
#
# Ubuntu
#
#--------------------------------
  - distribution: ubuntu-19.04
    playbook: sonar_scanner_3.3.0.1492
  - distribution: ubuntu-18.04
    playbook: sonar_scanner_3.3.0.1492
  - distribution: ubuntu-16.04
    playbook: sonar_scanner_3.3.0.1492
  - distribution: ubuntu-14.04
    playbook: sonar_scanner_3.3.0.1492

#--------------------------------
#
# Debian
#
#--------------------------------
  - distribution: debian-10
    playbook: sonar_scanner_3.3.0.1492
  - distribution: debian-9
    playbook: sonar_scanner_3.3.0.1492
  - distribution: debian-8
    playbook: sonar_scanner_3.3.0.1492

#--------------------------------
#
# Oraclelinux
#
#--------------------------------
  - distribution: oraclelinux-8
    playbook: sonar_scanner_3.3.0.1492
  - distribution: oraclelinux-7
    playbook: sonar_scanner_3.3.0.1492

#--------------------------------
#
# Amazonlinux
#
#--------------------------------
  - distribution: amazonlinux-2
    playbook: sonar_scanner_3.3.0.1492

#--------------------------------
#
# Opensuse
#
#--------------------------------
  - distribution: opensuse-15.1
    playbook: sonar_scanner_3.3.0.1492
  - distribution: opensuse-15
    playbook: sonar_scanner_3.3.0.1492
  - distribution: opensuse-42.3
    playbook: sonar_scanner_3.3.0.1492
  - distribution: opensuse-42.2
    playbook: sonar_scanner_3.3.0.1492
  - distribution: opensuse-13.2
    playbook: sonar_scanner_3.3.0.1492

#--------------------------------
#
# Archlinux
#
#--------------------------------
  - distribution: archlinux-rolling
    playbook: sonar_scanner_3.3.0.1492

#--------------------------------
#
# Gentoo
#
#--------------------------------
  - distribution: gentoo-stage3
    playbook: sonar_scanner_3.3.0.1492

before_install:
  - 'docker pull diodonfrost/${distribution}-ansible:latest'

install:
  - 'pip install -r requirements.txt'

script:
  - 'distribution=${distribution} molecule test -s ${playbook}'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
