---
# tasks file for ansible-role-sonar-scanner

- name: Include OS specific variables.
  include_vars: "{{ ansible_system }}.yml"

- name: Install sonar-scanner
  include_tasks: "setup-{{ ansible_system }}.yml"
